os: linux

language: python

addons:
  apt:
    packages:
    # for docs
    - graphviz

install: pip install tox

jobs:
  include:
  - python: "3.7"
    env: TOX_ENV=cov-travis
  - python: "3.7"
    env: TOX_ENV=static
  - python: "3.7"
    env: TOX_ENV=docs
  - python: "3.7"
    env: TOX_ENV=package

script: tox -e $TOX_ENV

after_success:
- test $TOX_ENV = docs && scripts/push-docs
